#!/usr/bin/env bash

mkdir -p "${1}/opt"
[ -d /opt/shopware-${2} ] || git clone -b v${2} --depth 1 https://github.com/shopware/shopware.git "${1}/opt/shopware-${2}"
cd "${1}/opt/shopware-${2}" && git reset --hard
chmod -R 755 "${1}/opt/shopware-${2}/var"
chmod -R 755 "${1}/opt/shopware-${2}/web"
chmod -R 755 "${1}/opt/shopware-${2}/files"
chmod -R 755 "${1}/opt/shopware-${2}/media"
chmod -R 755 "${1}/opt/shopware-${2}/engine/Shopware/Plugins/Community"
