#!/usr/bin/env bash

mkdir -p /opt
[ -d /opt/shopware-${SHOPWARE_VERSION} ] || git clone -b v${SHOPWARE_VERSION} --depth 1 https://github.com/shopware/shopware.git /opt/shopware-${SHOPWARE_VERSION}
cd /opt/shopware-${SHOPWARE_VERSION} && git reset --hard
chmod -R 755 /opt/shopware-${SHOPWARE_VERSION}/var && chmod -R 755 /opt/shopware-${SHOPWARE_VERSION}/web && chmod -R 755 /opt/shopware-${SHOPWARE_VERSION}/files && chmod -R 755 /opt/shopware-${SHOPWARE_VERSION}/media && chmod -R 755 /opt/shopware-${SHOPWARE_VERSION}/engine/shopware-${SHOPWARE_VERSION}/Plugins/Community
